on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:

  release:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get -yq update

      - name: Build
        run: |
          cd $GITHUB_WORKSPACE
          make

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: 'bin/*.nro'
